import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'dimi' at '05/02/17 5:39 PM' with Gradle 2.14.1
 *
 * @author dimi, @date 05/02/17 5:39 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    }
}
